src/EmployeesManagement.Web/Controllers/ActivityController.cs
using EmployeesManagement.Core.Interfaces.IServices;
using EmployeesManagement.Web.Interfaces.IViewConverters;
using Microsoft.AspNetCore.Mvc;

namespace EmployeesManagement.Web.Controllers
{
    public class ActivityController : Controller
    {
        private readonly IActivityService _activityService;
        private readonly IActivityViewConverter _activityViewConverter;

        public ActivityController(IActivityService activityService,
            IActivityViewConverter activityViewConverter)
        {
            _activityService = activityService;
            _activityViewConverter = activityViewConverter;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var activities = _activityService.GetAll();

            var activityViewModels = _activityViewConverter.ConvertModelsToViewModels(activities);

            return View(activityViewModels);
        }
    }
}

src/EmployeesManagement.Web/Controllers/CompanyController.cs
using EmployeesManagement.Core.Exceptions;
using EmployeesManagement.Core.Interfaces.IServices;
using EmployeesManagement.Web.Interfaces.IViewConverters;
using EmployeesManagement.Web.Models.Company;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace EmployeesManagement.Web.Controllers
{
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly ILegalFormService _legalFormService;
        private readonly IActivityService _activityService;
        private readonly ICompanyViewConverter _companyViewConverter;

        public CompanyController(ICompanyService companyService,
            ILegalFormService legalFormService,
            IActivityService activityService,
            ICompanyViewConverter companyViewConverter)
        {
            _companyService = companyService;
            _legalFormService = legalFormService;
            _activityService = activityService;
            _companyViewConverter = companyViewConverter;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var companiesDTOs = _companyService.GetAll();

            var companiesViews = _companyViewConverter.ConvertModelsToViewModels(companiesDTOs);

            return View(companiesViews);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new AddCompanySelectListViewModel()
            {
                LegalForms = new SelectList(_legalFormService.GetAllName()),
                Activities = new SelectList(_activityService.GetAllName())
            });
        }

        [HttpPost]
        public IActionResult Add(AddCompanySelectListViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var companyDTO = _companyViewConverter.ConvertAddViewModelToModel(model.AddCompanyViewModel);

                    _companyService.Add(companyDTO);

                    return RedirectToAction(nameof(Index));
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }

            model.LegalForms = new SelectList(_legalFormService.GetAllName());
            model.Activities = new SelectList(_activityService.GetAllName());

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var companyDTO = _companyService.Get(id);

            if (companyDTO == null)
            {
                return RedirectToAction("Error", "Home", new { requestId = "400", errorInfo = "Компания не найдена" });
            }

            return View(new EditCompanySelectListViewModel()
            {
                EditCompanyViewModel = _companyViewConverter.ConvertModelToEditViewModel(companyDTO),
                LegalForms = new SelectList(_legalFormService.GetAllName()),
                Activities = new SelectList(_activityService.GetAllName())
            });
        }

        [HttpPost]
        public IActionResult Edit(EditCompanySelectListViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var companyDTO = _companyViewConverter.ConvertEditViewModelToModel(model.EditCompanyViewModel);

                    _companyService.Edit(companyDTO);

                    return RedirectToAction(nameof(Index));
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }

            model.LegalForms = new SelectList(_legalFormService.GetAllName());
            model.Activities = new SelectList(_activityService.GetAllName());

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                _companyService.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { requestId = "500", errorInfo = string.Empty });
            }
        }
    }
}

src/EmployeesManagement.Web/Controllers/EmployeeController.cs
using EmployeesManagement.Core.Exceptions;
using EmployeesManagement.Core.Interfaces.IServices;
using EmployeesManagement.Web.Interfaces.IViewConverters;
using EmployeesManagement.Web.Models.Employee;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace EmployeesManagement.Web.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _empoyeeService;
        private readonly IPositionService _positionService;
        private readonly ICompanyService _companyService;
        private readonly IEmployeeViewConverter _employeeViewConverter;

        public EmployeeController(IEmployeeService empoyeeService,
            IPositionService positionService,
            ICompanyService companyService,
            IEmployeeViewConverter employeeViewConverter)
        {
            _empoyeeService = empoyeeService;
            _positionService = positionService;
            _companyService = companyService;
            _employeeViewConverter = employeeViewConverter;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var employeeDTOs = _empoyeeService.GetAll();

            var emoloyeeViews = _employeeViewConverter.ConvertModelsToViewModels(employeeDTOs);

            return View(emoloyeeViews);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new AddEmployeeSelectListViewModel()
            {
                AddEmployeeViewModel = new AddEmployeeViewModel() { DateEmployment = DateTime.Now },
                Positions = new SelectList(_positionService.GetAllName()),
                Companies = new SelectList(_companyService.GetAllName())
            });
        }

        [HttpPost]
        public IActionResult Add(AddEmployeeSelectListViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var employeeDTO = _employeeViewConverter.ConvertAddViewModelToModel(model.AddEmployeeViewModel);

                    _empoyeeService.Add(employeeDTO);

                    return RedirectToAction(nameof(Index));
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }

            model.Positions = new SelectList(_positionService.GetAllName());
            model.Companies = new SelectList(_companyService.GetAllName());

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var employeeDTO = _empoyeeService.Get(id);

            if (employeeDTO == null)
            {
                return RedirectToAction("Error", "Home", new { requestId = "400", errorInfo = "Сотрудник не найден" });
            }

            return View(new EditEmployeeSelectListViewModel()
            {
                EditEmployeeViewModel = _employeeViewConverter.ConvertModelToEditViewModel(employeeDTO),
                Companies = new SelectList(_companyService.GetAllName()),
                Positions = new SelectList(_positionService.GetAllName())
            });
        }

        [HttpPost]
        public IActionResult Edit(EditEmployeeSelectListViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var employeeDTO = _employeeViewConverter.ConvertEditViewModelToModel(model.EditEmployeeViewModel);

                    _empoyeeService.Edit(employeeDTO);

                    return RedirectToAction(nameof(Index));
                }
                catch (ValidationException ex)
                {
                    ModelState.AddModelError(ex.Property, ex.Message);
                }
            }

            model.Positions = new SelectList(_positionService.GetAllName());
            model.Companies = new SelectList(_companyService.GetAllName());

            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            try
            {
                _empoyeeService.Delete(id);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { requestId = "500", errorInfo = string.Empty });
            }
        }
    }
}

src/EmployeesManagement.Web/Controllers/PositionController.cs
using EmployeesManagement.Core.Interfaces.IServices;
using EmployeesManagement.Web.Interfaces.IViewConverters;
using Microsoft.AspNetCore.Mvc;

namespace EmployeesManagement.Web.Controllers
{
    public class PositionController : Controller
    {
        private readonly IPositionService _positionService;
        private readonly IPositionViewConverter _positionViewConverter;

        public PositionController(IPositionService positionService,
            IPositionViewConverter positionViewConverter)
        {
            _positionService = positionService;
            _positionViewConverter = positionViewConverter;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var positions = _positionService.GetAll();

            var positionViewModels = _positionViewConverter.ConvertModelsToViewModels(positions);

            return View(positionViewModels);
        }
    }
}

src/EmployeesManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item font-weight-bold">
                        @if ((Context.Request.Path.ToString() == "/" || Context.Request.Path.ToString().ToLower().Contains("home"))
                            && !Context.Request.Path.ToString().ToLower().Contains("privacy"))
                        {
                            <a class="nav-link active" asp-controller="Home" asp-action="Index">Управление персоналом</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Управление персоналом</a>
                        }
                    </li>
                    <li class="nav-item">
                        @if (Context.Request.Path.ToString().ToLower().Contains("employee"))
                        {
                            <a class="nav-link active" asp-controller="Employee" asp-action="Index">Работники</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Employee" asp-action="Index">Работники</a>
                        }
                    </li>
                    <li class="nav-item">
                        @if (Context.Request.Path.ToString().ToLower().Contains("company"))
                        {
                            <a class="nav-link active" asp-controller="Company" asp-action="Index">Компании</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Company" asp-action="Index">Компании</a>
                        }
                    </li>
                    <li class="nav-item">
                        @if (Context.Request.Path.ToString().ToLower().Contains("legalform"))
                        {
                            <a class="nav-link active" asp-controller="LegalForm" asp-action="Index">Орг-прав формы</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="LegalForm" asp-action="Index">Орг-прав формы</a>
                        }
                    </li>
                    <li class="nav-item">
                        @if (Context.Request.Path.ToString().ToLower().Contains("position"))
                        {
                            <a class="nav-link active" asp-controller="Position" asp-action="Index">Должности</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Position" asp-action="Index">Должности</a>
                        }
                    </li>
                    <li class="nav-item">
                        @if (Context.Request.Path.ToString().ToLower().Contains("activity"))
                        {
                            <a class="nav-link active" asp-controller="Activity" asp-action="Index">Виды деятельности</a>
                        }
                        else
                        {
                            <a class="nav-link" asp-controller="Activity" asp-action="Index">Виды деятельности</a>
                        }
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div style="margin-top: 5%; margin-bottom: 5%;" class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Управление персоналом - <a asp-area="" asp-controller="Home" asp-action="Privacy">Политика конфиденциальности</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>